import React from "react";

import { NuqsAdapter } from "nuqs/adapters/next/app";

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todo App Example",
  description: "Todo App Example generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <NuqsAdapter>{children}</NuqsAdapter>
      </body>
    </html>
  );
}
